name: Deploy Dev

on:
  push:
    branches:
      - development

env:
  CACHE_NODE_MODULES_PATH: |
    ~/.npm
    node_modules
    **/node_modules

jobs:
  cache:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.3.0'
      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: node-${{ hashFiles('**/package-lock.json')}}
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run test

  

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.3.0'

      - uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: node-${{ hashFiles('**/package-lock.json')}}
      - run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 1e3b30bddc085f36cbf4f8a3e4776ff9
          projectName: valor-jobs-browser-dev
          directory: dist/valor-growth/browser
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}