name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  CACHE_NODE_MODULES_PATH: |
    ~/.npm
    node_modules
    **/node_modules

jobs:
  cache:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: node-${{ hashFiles('**/package-lock.json' }}
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.3.0'

      - uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: node-${{ hashFiles('**/package-lock.json') }}
      - run: npm run build -- --base-href /valor-jobs-browser/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./dist/valor-growth/browser