name: Pull Request

on:
  pull_request

env:
  CACHE_NODE_MODULES_PATH: |
    ~/.npm
    node_modules
    **/node_modules

jobs:
  cache:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.3.0'
      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: node-${{ hashFiles('**/package-lock.json')}}
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

  test:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.3.0'

      - uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: node-${{ hashFiles('**/package-lock.json')}}
      - run: npm run ci:test

  build:
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.3.0'

      - uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: node-${{ hashFiles('**/package-lock.json')}}
      - run: npm run build